name: Fetch Markets

on:
  schedule:
    - cron: '15 2 * * *'   # every day at 02:15 UTC (10:15 AM Malaysia time)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.40

      - name: Fetch markets & build JSON
        run: |
          python scripts/fetch_markets.py

      - name: Commit changes if any
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add markets/markets.json
          git diff --cached --quiet || (git commit -m "chore(markets): update markets.json [skip ci]" && git push)
