name: Fetch News

on:
  schedule:
    - cron: '0 * * * *'   # every hour
  workflow_dispatch:       # allow manual runs

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser==6.0.11

      - name: Run news fetcher
        run: python scripts/fetch_news.py

      - name: Commit & push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add news/news.json
          if ! git diff --cached --quiet; then
            git commit -m "chore(news): update news.json [skip ci]"
            git push
          else
            echo "No news changes"
